name: Open today's issue

on:
  schedule:
    # Run at 00:00 (JST)
    - cron: "0 15 * * *"

jobs:
  open_habit_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Open issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Asia/Tokyo
        with:
          filename: .github/ISSUE_TEMPLATE/continuity.md
